# Generated by Django 2.2.12 on 2020-06-09 07:29

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='job_title')),
                ('lower_limit', models.PositiveIntegerField(default=0, null=True)),
                ('upper_limit', models.PositiveIntegerField(default=0, null=True)),
                ('job_requirements', models.TextField(blank=True)),
                ('job_category', models.PositiveIntegerField(choices=[(1, 'IT & Software Development'), (2, 'Products & Services'), (3, 'Marketing Strategy & Research'), (4, 'Writing & Transcription'), (5, 'Business & Customer Service'), (6, 'Agents & Referral Services'), (7, 'Data Entry'), (8, 'Other')], default=0, null=True)),
                ('job_link', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call Back',
                'verbose_name_plural': 'Mpesa Call Backs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('reference', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.TextField()),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=12, null=True, verbose_name='phone_number')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_token', models.PositiveIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eclid tokens',
            },
        ),
        migrations.CreateModel(
            name='SkillPromotePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_post_paid', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill Promote Payments',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD')], max_length=4, null=True)),
                ('quote_amount', models.PositiveIntegerField(default=0, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referralapp.Job')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referralapp.Profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Quotes',
            },
        ),
        migrations.CreateModel(
            name='MerchantPromote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=60)),
                ('business_description', models.TextField(blank=True)),
                ('business_charge', models.PositiveIntegerField(default=0, null=True)),
                ('business_link', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2020, 7, 9, 7, 28, 46, 629374, tzinfo=utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advertised Merchants',
            },
        ),
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_paid', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Payments',
            },
        ),
        migrations.CreateModel(
            name='FreelanceSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelance_skill', models.PositiveIntegerField(choices=[(1, 'Design & Creatives'), (2, 'Marketing'), (3, 'Websties & IT'), (4, 'Accounting'), (5, 'Legal'), (6, 'Business Consulting'), (7, 'Tutoring & Courses'), (8, 'Trading & Analysis'), (9, 'Event & Decorations'), (10, 'Personal Training'), (11, 'Writing & Transcription'), (12, 'Photography'), (13, 'Data Entry Expert')], default=0, null=True)),
                ('freelance_description', models.TextField(blank=True)),
                ('freelance_charge', models.PositiveIntegerField(default=0, null=True)),
                ('freelance_link', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2020, 7, 9, 7, 28, 46, 629980, tzinfo=utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advertised Skills',
            },
        ),
        migrations.CreateModel(
            name='BusinessPromotePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_post_paid', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Promote Payments',
            },
        ),
    ]
