# Generated by Django 2.2.12 on 2020-05-22 12:45

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='job_title')),
                ('sorted_pay', models.FloatField(choices=[(0.5, '0.5$-1.0$'), (1, '1.0$-1.5$'), (1.5, '1.5$-2.0$'), (2, '2.0$-2.5$'), (3, '3.0$-3.5$')], default=0.0)),
                ('job_completion', models.PositiveIntegerField(default=0, null=True)),
                ('job_requirements', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_price', models.IntegerField(choices=[(3, '3 credits - KES 300'), (5, '5 credits - KES 500'), (7, '7 credits - KES 700')], default=0)),
                ('bid_token', models.PositiveIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Job Tokens',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD')], max_length=4, null=True)),
                ('quote_amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referralapp.Job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Quotes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=10, null=True)),
                ('mpesa_code', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Confirmed',
            },
        ),
    ]
