# Generated by Django 2.2.12 on 2020-06-10 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceskills',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 9, 42, 0, 391327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchantpromote',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 9, 42, 0, 390546, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
