# Generated by Django 2.2.12 on 2020-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sorted_pay',
            field=models.FloatField(choices=[(0.5, '0.5$-1.0$'), (1, '1.0$-1.5$'), (1.5, '1.5$-2.0$'), (2, '2.0$-2.5$'), (3, '3.0$-3.5$')], default=None),
        ),
    ]
