# Generated by Django 2.2.12 on 2020-06-08 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceskills',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 23, 3, 33, 314169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='lower_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='upper_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchantpromote',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 23, 3, 33, 313627, tzinfo=utc)),
        ),
    ]
