# Generated by Django 2.2.12 on 2020-05-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0002_auto_20200522_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sorted_pay',
        ),
        migrations.AddField(
            model_name='job',
            name='lower_limit',
            field=models.FloatField(choices=[(0.5, '0.5$-1.0$'), (1, '1.0$-1.5$'), (1.5, '1.5$-2.0$'), (2, '2.0$-2.5$'), (3, '3.0$-3.5$')], default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='upper_limit',
            field=models.FloatField(choices=[(1.0, '0.5$-1.0$'), (1.5, '1.0$-1.5$'), (2.0, '1.5$-2.0$'), (2.5, '2.0$-2.5$'), (3.5, '3.0$-3.5$')], default=0.0),
        ),
    ]
