# Generated by Django 2.2.12 on 2020-06-09 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0002_auto_20200609_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceskills',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 7, 31, 31, 934589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchantpromote',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 7, 31, 31, 934059, tzinfo=utc)),
        ),
    ]
