# Generated by Django 2.2.12 on 2020-05-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0004_auto_20200525_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='typee',
            new_name='type',
        ),
    ]
