# Generated by Django 2.2.12 on 2020-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0005_auto_20200525_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=12, null=True, verbose_name='phone_number'),
        ),
    ]
