# Generated by Django 2.2.12 on 2020-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0006_profile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='confirmpayment',
            name='payment_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
