# Generated by Django 2.2.12 on 2020-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0007_auto_20200525_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='confirmpayment',
            name='mpesa_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
