# Generated by Django 2.2.12 on 2020-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0009_auto_20200525_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
