# Generated by Django 2.2.12 on 2020-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0010_auto_20200526_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lower_limit',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='upper_limit',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
