# Generated by Django 2.2.12 on 2020-05-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0013_auto_20200526_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
