# Generated by Django 2.2.12 on 2020-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0014_job_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_post_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
