# Generated by Django 2.2.12 on 2020-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0015_job_job_post_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Products & Services', 'Products & Services'), ('IT & Software', 'IT & Software'), ('Marketing & Social Media', 'Marketing & Social Media'), ('Writing & Transcription', 'Writing & Transcription'), ('Business & Customer Service', 'Business & Customer Service'), ('Agent & Referral', 'Agent & Referral'), ('Other', 'Other')], max_length=60),
        ),
    ]
