# Generated by Django 2.2.12 on 2020-05-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0016_auto_20200526_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Products & Services', 'Products & Services'), ('IT & Software Development', 'IT & Software Development'), ('Marketing & Social Media Strategy', 'Marketing & Social Media Strategy'), ('Writing & Transcription', 'Writing & Transcription'), ('Business & Customer Service', 'Business & Customer Service'), ('Agents & Referral Services', 'Agents & Referral Services'), ('Other', 'Other')], max_length=60),
        ),
    ]
