# Generated by Django 2.2.12 on 2020-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0017_auto_20200526_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='digital_category',
            field=models.CharField(blank=True, choices=[('Digital Media Marketing', 'Digital Media Marketing')], max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Products & Services', 'Products & Services'), ('IT & Software Development', 'IT & Software Development'), ('Marketing Strategy & Research', 'Marketing Strategy & Research'), ('Writing & Transcription', 'Writing & Transcription'), ('Business & Customer Service', 'Business & Customer Service'), ('Agents & Referral Services', 'Agents & Referral Services'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
