# Generated by Django 2.2.12 on 2020-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralapp', '0018_auto_20200527_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='digital_category',
            field=models.CharField(blank=True, choices=[('Digital Media Marketing', 'Digital Media Marketing'), ('E-commerce Specialist Required', 'I need an E-commerce Specialist')], max_length=60),
        ),
    ]
