# Generated by Django 2.2.12 on 2020-05-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referralapp', '0021_auto_20200528_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_post_paid',
        ),
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_paid', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Payment',
            },
        ),
    ]
